spring.application.name=markcraft
server.address=127.0.0.1
server.port=8080
markcraft.vault.root=${user.home}/.markcraft/vault
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-missing-creator-properties=true
